# Project 1: SAT & ACT Analysis

The first markdown cell in a notebook is a great place to provide an overview of your entire project. You will likely want to at least state your

## Problem Statement

Define the problem you are finding answers for from the data given.

## Executive Summary

If you want to, it's great to use relative links to direct your audience to various sections of a notebook. **HERE'S A DEMONSTRATION WITH THE CURRENT SECTION HEADERS**:

### Contents:
- [2017 Data Import & Cleaning](#Data-Import-and-Cleaning)
- [2018 Data Import and Cleaning](#2018-Data-Import-and-Cleaning)
- [Exploratory Data Analysis](#Exploratory-Data-Analysis)
- [Data Visualization](#Visualize-the-data)
- [Descriptive and Inferential Statistics](#Descriptive-and-Inferential-Statistics)
- [Outside Research](#Outside-Research)
- [Conclusions and Recommendations](#Conclusions-and-Recommendations)

**If you combine your problem statement, executive summary, data dictionary, and conclusions/recommendations, you have an amazing README.md file that quickly aligns your audience to the contents of your project.** Don't forget to cite your data sources!

*All libraries used should be added here*

In [1]:
import numpy as np
import pandas as pd



## 2017 Data Import and Cleaning

#### 1. Read In SAT & ACT  Data

Read in the `sat_2017.csv` and `act_2017.csv` files and assign them to appropriately named pandas dataframes.

In [2]:
sat_2017 = pd.read_csv('../data/sat_2017.csv')
act_2017 = pd.read_csv('../data/act_2017.csv')

#### 2. Display Data

Print the first 10 rows of each dataframe to your jupyter notebook

In [3]:
sat_2017.head(10)

State Participation  Evidence-Based Reading and Writing  \
0               Alabama            5%                                 593   
1                Alaska           38%                                 547   
2               Arizona           30%                                 563   
3              Arkansas            3%                                 614   
4            California           53%                                 531   
5              Colorado           11%                                 606   
6           Connecticut          100%                                 530   
7              Delaware          100%                                 503   
8  District of Columbia          100%                                 482   
9               Florida           83%                                 520   

   Math  Total  
0   572   1165  
1   533   1080  
2   553   1116  
3   594   1208  
4   524   1055  
5   595   1201  
6   512   1041  
7   492    996  
8   468    950  
9   497   1017

In [4]:
act_2017.tail(10)

State Participation  English  Math  Reading  Science Composite
42   South Dakota           80%     20.7  21.5     22.3     22.0      21.8
43      Tennessee          100%     19.5  19.2     20.1     19.9      19.8
44          Texas           45%     19.5  20.7     21.1     20.9      20.7
45           Utah          100%     19.5  19.9     20.8     20.6      20.3
46        Vermont           29%     23.3  23.1     24.4     23.2      23.6
47       Virginia           29%     23.5  23.3     24.6     23.5      23.8
48     Washington           29%     20.9  21.9     22.1     22.0      21.9
49  West Virginia           69%     20.0  19.4     21.2     20.5      20.4
50      Wisconsin          100%     19.7  20.4     20.6     20.9      20.5
51        Wyoming          100%     19.4  19.8     20.8     20.6     20.2x

In [5]:
print(sat_2017.info())
sat_2017.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column                              Non-Null Count  Dtype 
---  ------                              --------------  ----- 
 0   State                               51 non-null     object
 1   Participation                       51 non-null     object
 2   Evidence-Based Reading and Writing  51 non-null     int64 
 3   Math                                51 non-null     int64 
 4   Total                               51 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 2.1+ KB
None


State Participation  Evidence-Based Reading and Writing  \
count           51            51                           51.000000   
unique          51            34                                 NaN   
top     New Mexico            3%                                 NaN   
freq             1             8                                 NaN   
mean           NaN           NaN                          569.117647   
std            NaN           NaN                           45.666901   
min            NaN           NaN                          482.000000   
25%            NaN           NaN                          533.500000   
50%            NaN           NaN                          559.000000   
75%            NaN           NaN                          613.000000   
max            NaN           NaN                          644.000000   

              Math        Total  
count    51.000000    51.000000  
unique         NaN          NaN  
top            NaN          NaN  
freq           NaN          NaN  
mean    547.627451  1126.098039  
std      84.909119    92.494812  
min      52.000000   950.000000  
25%     522.000000  1055.500000  
50%     548.000000  1107.000000  
75%     599.000000  1212.000000  
max     651.000000  1295.000000

In [6]:
print(act_2017.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State          52 non-null     object 
 1   Participation  52 non-null     object 
 2   English        52 non-null     float64
 3   Math           52 non-null     float64
 4   Reading        52 non-null     float64
 5   Science        52 non-null     float64
 6   Composite      52 non-null     object 
dtypes: float64(4), object(3)
memory usage: 3.0+ KB
None


#### 3. Verbally Describe Data

Take your time looking through the data and thoroughly describe the data in the markdown cell below. 

### <I>Here are some flash findings based on the summary stats:
- Data from all 50 states are represented in both datasets, with an exception of ACT_2017 having an additional row for the entire nation. This row would affect our aggregate analysis and would <b>need to be removed</b>.
- Apart from the component test scores, both datasets also capture the participation rate
- Both datasets have an aggregate feature (Total column in SAT2017 - Sum & Composite column in ACT2017 - Mean)



#### 4a. Does the data look complete? 

### <I>Yes</I>.
There are no null values from both datasets.



#### 4b. Are there any obvious issues with the observations?


<details>
<summary>More Info</summary>

**What is the minimum *possible* value for each test/subtest? What is the maximum *possible* value?**

Consider comparing any questionable values to the sources of your data:
- [SAT](https://blog.collegevine.com/here-are-the-average-sat-scores-by-state/)
- [ACT](https://blog.prepscholar.com/act-scores-by-state-averages-highs-and-lows)
</details>

In [7]:
sat_2017.describe(include='all')

State Participation  Evidence-Based Reading and Writing  \
count           51            51                           51.000000   
unique          51            34                                 NaN   
top     New Mexico            3%                                 NaN   
freq             1             8                                 NaN   
mean           NaN           NaN                          569.117647   
std            NaN           NaN                           45.666901   
min            NaN           NaN                          482.000000   
25%            NaN           NaN                          533.500000   
50%            NaN           NaN                          559.000000   
75%            NaN           NaN                          613.000000   
max            NaN           NaN                          644.000000   

              Math        Total  
count    51.000000    51.000000  
unique         NaN          NaN  
top            NaN          NaN  
freq           NaN          NaN  
mean    547.627451  1126.098039  
std      84.909119    92.494812  
min      52.000000   950.000000  
25%     522.000000  1055.500000  
50%     548.000000  1107.000000  
75%     599.000000  1212.000000  
max     651.000000  1295.000000

In [8]:
sat_2017[sat_2017['Math'] == 52]['State']

20    Maryland
Name: State, dtype: object

In [9]:
act_2017.describe(include='all')

State Participation    English       Math    Reading    Science  \
count           52            52  52.000000  52.000000  52.000000  52.000000   
unique          52            28        NaN        NaN        NaN        NaN   
top     New Mexico          100%        NaN        NaN        NaN        NaN   
freq             1            17        NaN        NaN        NaN        NaN   
mean           NaN           NaN  20.919231  21.173077  22.001923  21.040385   
std            NaN           NaN   2.332132   1.963602   2.048672   3.151113   
min            NaN           NaN  16.300000  18.000000  18.100000   2.300000   
25%            NaN           NaN  19.000000  19.400000  20.475000  19.900000   
50%            NaN           NaN  20.550000  20.900000  21.700000  21.150000   
75%            NaN           NaN  23.300000  23.100000  24.125000  22.525000   
max            NaN           NaN  25.500000  25.300000  26.000000  24.900000   

       Composite  
count         52  
unique        38  
top         19.8  
freq           3  
mean         NaN  
std          NaN  
min          NaN  
25%          NaN  
50%          NaN  
75%          NaN  
max          NaN

In [10]:
act_2017[act_2017['Science'] == 2.3]['State']

21    Maryland
Name: State, dtype: object

### <I>Yes, there are errors in both datasets.</I>
#### SAT2017
The min value of the Math score seems to be an erroneus outlier. Crossreferenced the state with the official record and confirmed that the right value should be <b>524</b>.
#### ACT2017
The min value of the Science score seems to be an erroneus outlier. Crossreferenced the state with the official record and confirmed that the right value should be <b>22.3</b>.

#### 4c. Fix any errors you identified

**The data is available** so there's no need to guess or calculate anything. If you didn't find any errors, continue to the next step.

In [11]:
# change error in math col for SAT2017
sat_2017.loc[sat_2017['State'] == 'Maryland','Math'] = 524

# change error in science col for ACT2017
act_2017.loc[act_2017['State'] == 'Maryland','Science'] = 22.3

#### 5. What are your data types? 
Display the data types of each feature. 

What did you learn?
- Do any of them seem odd?  
- Which ones are not as they should be?  

In [12]:
print("ACT2017 dtypes")
print("-" * 50)
act_2017.info()

print('\n\n')

print("SAT2017 dtypes")
print("-" * 50)
sat_2017.info()

ACT2017 dtypes
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State          52 non-null     object 
 1   Participation  52 non-null     object 
 2   English        52 non-null     float64
 3   Math           52 non-null     float64
 4   Reading        52 non-null     float64
 5   Science        52 non-null     float64
 6   Composite      52 non-null     object 
dtypes: float64(4), object(3)
memory usage: 3.0+ KB



SAT2017 dtypes
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column                              Non-Null Count  Dtype 
---  ------                              --------------  ----- 
 0   State                               51 non-null     object
 1   Participation   

### <i> There are 2 main errors: </i>

1) The Participation rate on both datasets should be an integer value


2) The Composite column in ACT2017 seems to be filled with float numbers yet it's returning an object dtype.



#### 6. Fix Incorrect Data Types
Based on what you discovered above, use appropriate methods to re-type incorrectly typed data.
- Define a function that will allow you to convert participation rates to an appropriate numeric type. Use `map` or `apply` to change these columns in each dataframe.

In [13]:
def convert_partic_rate(value):
    return int(value.split('%')[0])

act_2017['Participation'] = act_2017['Participation'].apply(convert_partic_rate)
sat_2017['Participation'] = sat_2017['Participation'].apply(convert_partic_rate)

- Fix any individual values preventing other columns from being the appropriate type.

In [14]:
# to detect where the problem lies in the column
act_2017['Composite'].value_counts()

act_2017['Composite'] = act_2017['Composite'].apply(lambda y: float(y.split('x')[0]) if 'x' in y else float(y))

- Display the data types again to confirm they are correct.

In [15]:
act_2017.dtypes

State             object
Participation      int64
English          float64
Math             float64
Reading          float64
Science          float64
Composite        float64
dtype: object

#### 7. Rename Columns
Change the names of the columns to more expressive names so that you can tell the difference the SAT columns and the ACT columns. Your solution should map all column names being changed at once (no repeated singular name-changes). **We will be combining these data with some of the data from 2018, and so you should name columns in an appropriate way**.

**Guidelines**:
- Column names should be all lowercase (you will thank yourself when you start pushing data to SQL later in the course)
- Column names should not contain spaces (underscores will suffice--this allows for using the `df.column_name` method to access columns in addition to `df['column_name']`.
- Column names should be unique and informative (the only feature that we actually share between dataframes is the state).

In [16]:
new_act_col_names = list(act_2017.columns)
new_sat_col_names = list(sat_2017.columns)

In [17]:
new_act_col_names = [str("act2017_" + name.lower()) for name in new_act_col_names]
new_act_col_names[0] = new_act_col_names[0].split("act2017_")[1]
act_2017.set_axis(new_act_col_names, axis='columns', inplace=True)

In [18]:
act_2017.head()

state  act2017_participation  act2017_english  act2017_math  \
0  National                     60             20.3          20.7   
1   Alabama                    100             18.9          18.4   
2    Alaska                     65             18.7          19.8   
3   Arizona                     62             18.6          19.8   
4  Arkansas                    100             18.9          19.0   

   act2017_reading  act2017_science  act2017_composite  
0             21.4             21.0               21.0  
1             19.7             19.4               19.2  
2             20.4             19.9               19.8  
3             20.1             19.8               19.7  
4             19.7             19.5               19.4

In [19]:
new_sat_col_names = [str("sat2017_" + name.lower()) for name in new_sat_col_names]
new_sat_col_names[0] = new_sat_col_names[0].split("sat2017_")[1]
sat_2017.set_axis(new_sat_col_names, axis='columns', inplace=True)

In [20]:
sat_2017.rename(columns={'sat2017_evidence-based reading and writing':'sat2017_rw'},inplace=True)
sat_2017.head()

state  sat2017_participation  sat2017_rw  sat2017_math  sat2017_total
0     Alabama                      5         593           572           1165
1      Alaska                     38         547           533           1080
2     Arizona                     30         563           553           1116
3    Arkansas                      3         614           594           1208
4  California                     53         531           524           1055

#### 8. Create a data dictionary

Now that we've fixed our data, and given it appropriate names, let's create a [data dictionary](http://library.ucmerced.edu/node/10249). 

A data dictionary provides a quick overview of features/variables/columns, alongside data types and descriptions. The more descriptive you can be, the more useful this document is.

Example of a Fictional Data Dictionary Entry: 

|Feature|Type|Dataset|Description|
|---|---|---|---|
|**county_pop**|*integer*|2010 census|The population of the county (units in thousands, where 2.5 represents 2500 people).| 
|**per_poverty**|*float*|2010 census|The percent of the county over the age of 18 living below the 200% of official US poverty rate (units percent to two decimal places 98.10 means 98.1%)|

[Here's a quick link to a short guide for formatting markdown in Jupyter notebooks](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html).

Provided is the skeleton for formatting a markdown table, with columns headers that will help you create a data dictionary to quickly summarize your data, as well as some examples. **This would be a great thing to copy and paste into your custom README for this project.**

## Data Dictionary for act_2017/sat_2017

|Feature|Type|Dataset|Description|
|-------|----|-------|------------|
|"name_of_dataset"_state|object|act_2017/sat_2017|States that participated in the ACT/SAT examination|
|"name_of_dataset"_participation|integer|act2017/sat2017|State participation rates (%)|
|act2017_english|float|act_2017|Average English Score which ranges between 1 and 36|
|act2017_math|	float|act_2017|	Average Math Score which ranges between 1 and 36|
|act2017_reading|	float|act_2017|	Average Reading Score which ranges between 1 and 36|
|act2017_science|	float|act_2017|	Average Science Score which ranges between 1 and 36|
|act2017_composite|	float|act_2017|	Average Composite Score which ranges between 1 and 36|
|sat2017_rw|integer|sat_2017|	Average Evidence-Based Reading and Writing Score which ranges between 200 and 800|
|sat2017_math|integer|sat_2017|	Average Math Score which ranges between 200 and 800|
|sat2017_total|integer|sat_2017|	Average Total Score that aggregates Reading and Writing and Math Scores, ranges between 400 and 1600|



#### 9. Drop unnecessary rows

One of our dataframes contains an extra row. Identify and remove this from the dataframe.

In [21]:
act_2017 = act_2017[act_2017['state'] != 'National']

#### 10. Merge Dataframes

Join the 2017 ACT and SAT dataframes using the state in each dataframe as the key. Assign this to a new variable.

In [22]:
combined_2017 = pd.merge(sat_2017,act_2017, on='state')

#### 11. Save your cleaned, merged dataframe

Use a relative path to save out your data as `combined_2017.csv`.

In [23]:
combined_2017.to_csv('../data/combined_2017.csv')

## 2018 Data Import and Cleaning

Links to the 2018 ACT and SAT data are provided in the README. These data live in PDFs, and so you'll get to enjoy practicing some *manual* data collection. Save these data as a CSV in your `data` directory, and import, explore, and clean these data in the same way you did above. **Make sure you comment on your steps so it is clear *why* you are doing each process**.

### importing 2018 data

In [24]:
act_2018 = pd.read_csv('../data/act_2018_updated.csv')
sat_2018 = pd.read_csv('../data/sat_2018.csv')

In [25]:
sat_2018.info()
print('\n')
print(sat_2018.head())
sat_2018.describe().round(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column                              Non-Null Count  Dtype 
---  ------                              --------------  ----- 
 0   State                               51 non-null     object
 1   Participation                       51 non-null     object
 2   Evidence-Based Reading and Writing  51 non-null     int64 
 3   Math                                51 non-null     int64 
 4   Total                               51 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 2.1+ KB


        State Participation  Evidence-Based Reading and Writing  Math  Total
0     Alabama            6%                                 595   571   1166
1      Alaska           43%                                 562   544   1106
2     Arizona           29%                                 577   572   1149
3    Arkansas            5%                                 592   576   1169
4  California

Evidence-Based Reading and Writing    Math    Total
count                               51.00   51.00    51.00
mean                               563.69  556.24  1120.02
std                                 47.50   47.77    94.16
min                                480.00  480.00   977.00
25%                                534.50  522.50  1057.50
50%                                552.00  544.00  1098.00
75%                                610.50  593.50  1204.00
max                                643.00  655.00  1298.00

In [26]:
act_2018.info()
print('\n')
print(act_2018.head())
act_2018.describe().round(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   State                          51 non-null     object 
 1   Percentage of Students Tested  51 non-null     int64  
 2   Average Composite Score        51 non-null     float64
 3   Average English Score          51 non-null     float64
 4   Average Math Score             51 non-null     float64
 5   Average Reading Score          51 non-null     float64
 6   Average Science Score          51 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 2.9+ KB


        State  Percentage of Students Tested  Average Composite Score  \
0     Alabama                            100                     19.1   
1      Alaska                             33                     20.8   
2     Arizona                             66                     19.2   
3 

Percentage of Students Tested  Average Composite Score  \
count                          51.00                    51.00   
mean                           61.65                    21.49   
std                            34.08                     2.11   
min                             7.00                    17.70   
25%                            28.50                    19.95   
50%                            66.00                    21.30   
75%                           100.00                    23.55   
max                           100.00                    25.60   

       Average English Score  Average Math Score  Average Reading Score  \
count                  51.00               51.00                  51.00   
mean                   20.99               21.13                  22.02   
std                     2.45                2.04                   2.17   
min                    16.60               17.80                  18.00   
25%                    19.10               19.40                  20.45   
50%                    20.20               20.70                  21.60   
75%                    23.70               23.15                  24.10   
max                    26.00               25.20                  26.10   

       Average Science Score  
count                  51.00  
mean                   21.35  
std                     1.87  
min                    17.90  
25%                    19.85  
50%                    21.10  
75%                    23.05  
max                    24.90

### exploring and cleaning 2018 data

At a snapshot, we can observe the following from both datasets:


#### <I>SAT_2018</I>
- ** Participation column needs to be converted to integer
- ** column names to be changed
- No other anomaly in the data


#### <I>ACT_2018</I>
- No anomaly in the data
- ** column names to be changed 

In [27]:
# modify participation column to int in SAT_2018

sat_2018['Participation'] = sat_2018['Participation'].apply(convert_partic_rate)

In [28]:
# change column names in both datasets
new_act_col_names = list(act_2018.columns)
new_sat_col_names = list(sat_2018.columns)

In [29]:
new_sat_col_names[1:] = [str("sat2018_" + name.lower()) for name in new_sat_col_names[1:]]
new_sat_col_names[0] = new_sat_col_names[0].lower()
sat_2018.set_axis(new_sat_col_names, axis='columns', inplace=True)
sat_2018.rename(columns={'sat2018_evidence-based reading and writing':'sat2018_rw'},inplace=True)


# ignore first 2 entries in list and do .split x2 + act2018_
new_act_col_names[2:] = [str("act2018_" + name.lower().split('average ')[1].split(' score')[0]) for name in new_act_col_names[2:]]
# change act2018_percentage of students tested to act2018_participation
new_act_col_names[1] = "act2018_participation"
new_act_col_names[0] = new_act_col_names[0].lower()
act_2018.set_axis(new_act_col_names, axis='columns', inplace=True)

In [47]:
print(f"Here are the new dtypes for sat_2018: \n\n{sat_2018.dtypes}")
print('\n')
print(f"Here are the new dtypes for act_2018: \n\n{act_2018.dtypes}")

Here are the new dtypes for sat_2018: 

state                    object
sat2018_participation     int64
sat2018_rw                int64
sat2018_math              int64
sat2018_total             int64
dtype: object


Here are the new dtypes for act_2018: 

state                     object
act2018_participation      int64
act2018_composite        float64
act2018_english          float64
act2018_math             float64
act2018_reading          float64
act2018_science          float64
dtype: object


#### Combine your 2017 and 2018 data into a single dataframe
Joining on state names should work, assuming you formatted all your state names identically. Make sure none of your columns (other than state) have identical names. Do yourself a favor and decide if you're encoding participation rates as floats or integers and standardize this across your datasets.

Save the contents of this merged dataframe as `final.csv`.

**Use this combined dataframe for the remainder of the project**.

In [52]:
final1_csv = pd.merge(act_2018,sat_2018, on='state')
final = pd.merge(combined_2017,final1_csv, on='state')

final.to_csv('../data/final.csv')

## Exploratory Data Analysis


### Summary Statistics
Transpose the output of pandas `describe` method to create a quick overview of each numeric feature.

In [54]:
final.describe().transpose().round(2)

count     mean    std    min      25%     50%      75%  \
sat2017_participation   51.0    39.80  35.28    2.0     4.00    38.0    66.00   
sat2017_rw              51.0   569.12  45.67  482.0   533.50   559.0   613.00   
sat2017_math            51.0   556.88  47.12  468.0   523.50   548.0   599.00   
sat2017_total           51.0  1126.10  92.49  950.0  1055.50  1107.0  1212.00   
act2017_participation   51.0    65.25  32.14    8.0    31.00    69.0   100.00   
act2017_english         51.0    20.93   2.35   16.3    19.00    20.7    23.30   
act2017_math            51.0    21.18   1.98   18.0    19.40    20.9    23.10   
act2017_reading         51.0    22.01   2.07   18.1    20.45    21.8    24.15   
act2017_science         51.0    21.43   1.73   18.2    19.95    21.3    22.75   
act2017_composite       51.0    21.52   2.02   17.8    19.80    21.4    23.60   
act2018_participation   51.0    61.65  34.08    7.0    28.50    66.0   100.00   
act2018_composite       51.0    21.49   2.11   17.7    19.95    21.3    23.55   
act2018_english         51.0    20.99   2.45   16.6    19.10    20.2    23.70   
act2018_math            51.0    21.13   2.04   17.8    19.40    20.7    23.15   
act2018_reading         51.0    22.02   2.17   18.0    20.45    21.6    24.10   
act2018_science         51.0    21.35   1.87   17.9    19.85    21.1    23.05   
sat2018_participation   51.0    45.75  37.31    2.0     4.50    52.0    77.50   
sat2018_rw              51.0   563.69  47.50  480.0   534.50   552.0   610.50   
sat2018_math            51.0   556.24  47.77  480.0   522.50   544.0   593.50   
sat2018_total           51.0  1120.02  94.16  977.0  1057.50  1098.0  1204.00   

                          max  
sat2017_participation   100.0  
sat2017_rw              644.0  
sat2017_math            651.0  
sat2017_total          1295.0  
act2017_participation   100.0  
act2017_english          25.5  
act2017_math             25.3  
act2017_reading          26.0  
act2017_science          24.9  
act2017_composite        25.5  
act2018_participation   100.0  
act2018_composite        25.6  
act2018_english          26.0  
act2018_math             25.2  
act2018_reading          26.1  
act2018_science          24.9  
sat2018_participation   100.0  
sat2018_rw              643.0  
sat2018_math            655.0  
sat2018_total          1298.0

#### Manually calculate standard deviation

$$\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^n(x_i - \mu)^2}$$

- Write a function to calculate standard deviation using the formula above

In [59]:
def std_dev(data):
    sd = 0.0
    for each in data:
        sd += (float(each) - np.mean(data))**2
    sd = (sd / float(len(data)))**0.5

    return sd

- Use a **dictionary comprehension** to apply your standard deviation function to each numeric column in the dataframe.  **No loops**  
- Assign the output to variable `sd` as a dictionary where: 
    - Each column name is now a key 
    - That standard deviation of the column is the value 
     
*Example Output :* `{'ACT_Math': 120, 'ACT_Reading': 120, ...}`

In [66]:
std_dev_dict = {}
checklist = list(final.describe().columns)
for column in checklist:
    std_dev_dict[column] = round(std_dev(final[column]),2)
std_dev_dict

{'sat2017_participation': 34.93,
 'sat2017_rw': 45.22,
 'sat2017_math': 46.66,
 'sat2017_total': 91.58,
 'act2017_participation': 31.82,
 'act2017_english': 2.33,
 'act2017_math': 1.96,
 'act2017_reading': 2.05,
 'act2017_science': 1.71,
 'act2017_composite': 2.0,
 'act2018_participation': 33.75,
 'act2018_composite': 2.09,
 'act2018_english': 2.42,
 'act2018_math': 2.02,
 'act2018_reading': 2.15,
 'act2018_science': 1.85,
 'sat2018_participation': 36.95,
 'sat2018_rw': 47.03,
 'sat2018_math': 47.3,
 'sat2018_total': 93.23}

Do your manually calculated standard deviations match up with the output from pandas `describe`? What about numpy's `std` method?

#### No, they don't.
In standard statistical practice, ddof=1 provides an unbiased estimator of the variance of the infinite population. ddof=0 provides a maximum likelihood estimate of the variance for normally distributed variables. The standard deviation computed in this function is the square root of the estimated variance, so even with ddof=1, it will not be an unbiased estimate of the standard deviation per se.

#### Investigate trends in the data
Using sorting and/or masking (along with the `.head` method to not print our entire dataframe), consider the following questions:

- Which states have the highest and lowest participation rates for the:
    - 2017 SAT?
    - 2018 SAT?
    - 2017 ACT?
    - 2018 ACT?
- Which states have the highest and lowest mean total/composite scores for the:
    - 2017 SAT?
    - 2018 SAT?
    - 2017 ACT?
    - 2018 ACT?
- Do any states with 100% participation on a given test have a rate change year-to-year?
- Do any states show have >50% participation on *both* tests either year?

Based on what you've just observed, have you identified any states that you're especially interested in? **Make a note of these and state *why* you think they're interesting**.

**You should comment on your findings at each step in a markdown cell below your code block**. Make sure you include at least one example of sorting your dataframe by a column, and one example of using boolean filtering (i.e., masking) to select a subset of the dataframe.

In [34]:
#code

## Visualize the data

There's not a magic bullet recommendation for the right number of plots to understand a given dataset, but visualizing your data is *always* a good idea. Not only does it allow you to quickly convey your findings (even if you have a non-technical audience), it will often reveal trends in your data that escaped you when you were looking only at numbers.

Some recommendations on plotting:
- Plots have titles
- Plots have axis labels
- Plots have appropriate tick labels
- All text is legible in a plot
- Plots demonstrate meaningful and valid relationships
- Plots are interpreted to aid understanding

There is such a thing as too many plots, and there are a *lot* of bad plots. You might make some! (But hopefully not with the guided prompts below).

#### Use Seaborn's heatmap with pandas `.corr()` to visualize correlations between all numeric features

Heatmaps are generally not appropriate for presentations, and should often be excluded from reports as they can be visually overwhelming. **However**, they can be extremely useful in identify relationships of potential interest (as well as identifying potential collinearity before modeling).

*example*:
```python
sns.heatmap(df.corr())
```

Please take time to format your output, adding a title. Look through some of the additional arguments and options. (Axis labels aren't really necessary, as long as the title is informative).

#### Define a custom function to subplot histograms

We have data for two tests for two years. We only have composite (and not subtest scores) for the 2018 ACT. We should write a function that will take the names of 2+ columns and subplot histograms. While you can use pandas plotting or Seaborn here, matplotlib gives you greater control over all aspects of your plots.

[Helpful Link for Plotting Multiple Figures](https://matplotlib.org/users/pyplot_tutorial.html#working-with-multiple-figures-and-axes)

Here's some starter code:

In [35]:
def subplot_histograms(dataframe, list_of_columns, list_of_titles, list_of_xlabels):
    nrows = int(np.ceil(len(list_of_columns)/2)) # Makes sure you have enough rows
    fig, ax = plt.subplots(nrows=nrows, ncols=2) # You'll want to specify your figsize
    ax = ax.ravel() # Ravel turns a matrix into a vector, which is easier to iterate
    for i, column in enumerate(list_of_columns): # Gives us an index value to get into all our lists
        ax[i].hist(dataframe[column]) # feel free to add more settings
        # Set titles, labels, etc here for each subplot

#### Plot and interpret histograms 
For each of the following:
- Participation rates for SAT & ACT
- Math scores for SAT & ACT
- Reading/verbal scores for SAT & ACT

In [36]:
# Code

#### Plot and interpret scatter plots

For each of the following:
- SAT vs. ACT math scores for 2017
- SAT vs. ACT verbal/reading scores for 2017
- SAT vs. ACT total/composite scores for 2017
- Total scores for SAT 2017 vs. 2018
- Composite scores for ACT 2017 vs. 2018

Plot the two variables against each other using matplotlib or Seaborn

Your plots should show:
- Two clearly labeled axes
- A proper title
- Using colors and symbols that are clear and unmistakable

**Feel free to write a custom function, and subplot if you'd like.** Functions save both time and space.


In [37]:
# Code

#### Plot and interpret boxplots

For each numeric variable in the dataframe create a boxplot using Seaborn. Boxplots demonstrate central tendency and spread in variables. In a certain sense, these are somewhat redundant with histograms, but you may be better able to identify clear outliers or differences in IQR, etc.

Multiple values can be plotted to a single boxplot as long as they are of the same relative scale (meaning they have similar min/max values).

Each boxplot should:
- Only include variables of a similar scale
- Have clear labels for each variable
- Have appropriate titles and labels

In [38]:
# Code

#### Feel free to do additional plots below
*(do research and choose your own chart types & variables)*

Are there any additional trends or relationships you haven't explored? Was there something interesting you saw that you'd like to dive further into? It's likely that there are a few more plots you might want to generate to support your narrative and recommendations that you are building toward. **As always, make sure you're interpreting your plots as you go**.

#### (Optional): Using Tableau, create a choropleth map for each variable using a map of the US. 

Save this plot as an image file in an images directory, provide a relative path, and insert the image into notebook in markdown.

## Descriptive and Inferential Statistics

#### Summarizing Distributions

Above, we used pandas `describe` to provide quick summary statistics of our numeric columns. We also demonstrated many visual relationships.

As data scientists, having a complete understanding of data is imperative prior to modeling.

While we will continue to build our analytic tools, we know that measures of *central tendency*, *spread*, and *shape/skewness* provide a quick summary of distributions.

For each variable in your data, summarize the underlying distributions (in words & statistics)
 - Be thorough in your verbal description of these distributions.
 - Be sure to back up these summaries with statistics.

Answers:


#### Distributions in the data

In this dataset, each data represents a sample from a population.                        
For example, for ACT math test:
- Population: the test results of all the students who take this test, nation-wide.
- Population mean: is the national average of ACT math test (total scores/total no. of test takers) 
- Sample: the state means of ACT math test. We have 51 samples (51 states)

***According to CLT, we generally assuming that data we sample from a population will be normally distributed. Do we observe this trend?***

Answer:

Does This Assumption Hold for:
    - Math
    - Reading
    - Rates
Explain your answers for each distribution and how you think this will affect estimates made from these data.

Answer:

#### Estimate Limits of Data

Suppose we only seek to understand the relationship between SAT and ACT participation rates in 2017. 

##### Does it make sense to conduct statistical inference given these data specifically? 

Why or why not?

*(think about granularity, aggregation, the relationships between populations size & rates...consider the actually populations these data describe in answering this question)*

Answer:

##### Is it appropriate to compare *these* specific SAT and ACT math scores  - can we say students with higher SAT math score is better than those with lower ACT math score, or vice versa?

Why or why not?

Answer:

#### Statistical Evaluation of Distributions 

**If you feel it's appropriate**, using methods we discussed in class, run hypothesis tests to compare variables of interest in our dataset. 

In [39]:
# Code:

## Outside Research

Based upon your observations, choose **three** states that demonstrate interesting trends in their SAT and/or ACT participation rates. Spend some time doing outside research on state policies that might influence these rates, and summarize your findings below. **Feel free to go back and create new plots that highlight these states of interest**. If you bring in any outside tables or charts, make sure you are explicit about having borrowed them. If you quote any text, make sure that it renders as being quoted. (Make sure that you cite your sources -- check with you local instructor for citation preferences).

## Conclusions and Recommendations

Based on your exploration of the data, what are you key takeaways and recommendations? Choose one state with a lower participation rate and provide a suggestion for how the College Board might increase participation amongst graduating seniors in this state. Are there additional data you desire that would better inform your investigations?